In [105]:
import io
import csv
import requests
import pandas as pd
import datetime

In [106]:
#get tickers we want data for
class gitHubData:
    def __init__ (self):
        #get tickers of interest from github repository
        self.ticker_url = "https://raw.githubusercontent.com/chipuha/StockMarket/master/Data/DowJonesTickers.txt"
        self.tickers = pd.read_csv(self.ticker_url)
        self.dataBaseUrl = "https://raw.githubusercontent.com/chipuha/StockMarket/master/Data/data/"
    
    #Returns data frame of values for specified ticker within specified range (INCLUSIVE)
    #ticker needs to be a string and in github list
    #startDate and endDate need to be datetime.datetime() objects
    def getData(self,ticker,startDate,endDate):
        self.ticker = ticker
        self.start = startDate
        self.end = endDate
        if self.start >= self.end:
            raise ValueError("\n----- Error -----\nStart date cannot be the same as or later than end date.")
        if not(self.ticker in self.tickers.values):
            raise ValueError("\n----- Error -----\n"+self.ticker+" is not in database.\nAdd ticker to database.")
        else:
            self.df = pd.read_csv(self.dataBaseUrl+self.ticker+".csv")
            try:
                #convert datatime.datetimes to strings to compare with dataframe dates which are strings
                self.start = self.start.strftime("%Y-%m-%d")
                self.end = self.end.strftime("%Y-%m-%d")

                #check github database contains desired ranges
                if self.df[self.df['Date'] <= self.start].empty:
                    raise ValueError("\n----- Error -----\nStart date is too early. Consider updating database.")
                if self.df[self.df['Date'] >= self.end].empty:
                    raise ValueError("\n----- Error -----\nEnd date is too recent. Database has not yet updated.")
                
                #new dataframe will INCLUDE the start and end dates
                self.df = self.df[self.df['Date'] >= self.start]
                self.df = self.df[self.df['Date'] <= self.end]
                return self.df
            except ValueError as e:
                raise

    
    def getTickerList(self):
        return self.tickers
    
    def getAvailableDateRange(self,ticker):
        self.ticker = ticker
        
        if not(self.ticker in self.tickers.values):
            raise ValueError("\n----- Error -----\n"+self.ticker+" is not in database.\nAdd ticker to database.")
        else:
            self.df = pd.read_csv(self.dataBaseUrl+self.ticker+".csv")
            first = self.df['Date'].values[0]
            last = self.df['Date'].values[-1]
            return [first, last] #first and last should be strings

In [114]:
dataStream = gitHubData()
dataStream.getData("AAPL",datetime.datetime(2006,1,7),datetime.datetime(2018,11,1))

,Unnamed: 0,Unnamed: 0.1,Date,Open,High,Low,Close,Adj Close,Volume
797,797,797,2006-01-09,10.961429,11.028571,10.820000,10.864285,9.628536,168760200
798,798,798,2006-01-10,10.892858,11.698571,10.832857,11.551429,10.237520,569967300
799,799,799,2006-01-11,11.977143,12.114285,11.798572,11.985714,10.622409,373448600
800,800,800,2006-01-12,12.138572,12.342857,11.945714,12.041429,10.671784,320202400
801,801,801,2006-01-13,12.141429,12.287143,12.085714,12.227143,10.836376,194076400
802,802,802,2006-01-17,12.242857,12.340000,11.981428,12.101429,10.724963,208905900
803,803,803,2006-01-18,11.868571,12.007143,11.692857,11.784286,10.443892,300159300
804,804,804,2006-01-19,11.607142,11.665714,11.248571,11.291429,10.007092,423962000
805,805,805,2006-01-20,11.325714,11.434286,10.832857,10.870000,9.633601,283689700
806,806,806,2006-01-23,10.871428,11.365714,10.857142,11.095715,9.833642,264932500
807,807,807,2006-01-24,11.251429,11.345715,10.824286,10.862857,9.627270,285563600
808,808,808,2006-01-25,11.055715,11.071428,10.464286,10.600000,9.394312,318946600
809,809,809,2006-01-26,10.647142,10.775714,10.275714,10.332857,9.157555,295346800
810,810,810,2006-01-27,10.421429,10.514286,10.157143,10.290000,9.119573,238466200
811,811,811,2006-01-30,10.167143,10.942857,10.124286,10.714286,9.495598,349600300
812,812,812,2006-01-31,10.785714,10.905714,10.535714,10.787143,9.560169,228385500
813,813,813,2006-02-01,10.707143,10.922857,10.662857,10.774285,9.548771,130296600
814,814,814,2006-02-02,10.728572,10.765715,10.292857,10.300000,9.128431,176830500
815,815,815,2006-02-03,10.320000,10.398571,10.148571,10.264286,9.096784,173030900
816,816,816,2006-02-06,10.288571,10.358571,9.534286,9.614285,8.520717,412941900
817,817,817,2006-02-07,9.752857,9.925714,9.525714,9.657143,8.558699,347207700
818,818,818,2006-02-08,9.784286,9.868571,9.428572,9.830000,8.711895,238278600
819,819,819,2006-02-09,9.871428,9.890000,9.218572,9.278571,8.223186,287441000
820,820,820,2006-02-10,9.311429,9.667143,8.985714,9.615714,8.521981,440119400
821,821,821,2006-02-13,9.518572,9.535714,9.234285,9.244286,8.192804,220874500
822,822,822,2006-02-14,9.300000,9.728572,9.285714,9.662857,8.563765,290234700
823,823,823,2006-02-15,9.594286,9.945714,9.535714,9.888572,8.763803,289942800
824,824,824,2006-02-16,9.987143,10.144286,9.925714,10.081429,8.934723,237043800
825,825,825,2006-02-17,10.042857,10.127143,9.944285,10.041429,8.899275,143999800
826,826,826,2006-02-21,10.084286,10.114285,9.811429,9.868571,8.746077,194901700
...,...,...,...,...,...,...,...,...,...
3995,3995,3995,2018-09-21,220.779999,221.360001,217.289993,217.660004,217.660004,96246700
3996,3996,3996,2018-09-24,216.820007,221.259995,216.630005,220.789993,220.789993,27693400
3997,3997,3997,2018-09-25,219.750000,222.820007,219.699997,222.190002,222.190002,24554400
3998,3998,3998,2018-09-26,221.000000,223.750000,219.759995,220.419998,220.419998,23984700
3999,3999,3999,2018-09-27,223.820007,226.440002,223.539993,224.949997,224.949997,30181200
4000,4000,4000,2018-09-28,224.789993,225.839996,224.020004,225.740005,225.740005,22929400
4001,4001,4001,2018-10-01,227.949997,229.419998,226.350006,227.259995,227.259995,23600800
4002,4002,4002,2018-10-02,227.250000,230.000000,226.630005,229.279999,229.279999,24788200
4003,4003,4003,2018-10-03,230.050003,233.470001,229.779999,232.070007,232.070007,28654800
4004,4004,4004,2018-10-04,230.779999,232.350006,226.729996,227.990005,227.990005,32042000
4005,4005,4005,2018-10-05,227.960007,228.410004,220.580002,224.289993,224.289993,33580500
4006,4006,4006,2018-10-08,222.210007,224.800003,220.199997,223.770004,223.770004,29663900
4007,4007,4007,2018-10-09,223.639999,227.270004,222.250000,226.869995,226.869995,26891000
4008,4008,4008,2018-10-10,225.460007,226.350006,216.050003,216.360001,216.360001,41990600
4009,4009,4009,2018-10-11,214.520004,219.500000,212.320007,214.449997,214.449997,53124400
4010,4010,4010,2018-10-12,220.419998,222.880005,216.839996,222.110001,222.110001,40337900
4011,4011,4011,2018-10-15,221.160004,221.830002,217.270004,217.360001,217.360001,30791000
4012,4012,4012,2018-10-16,218.929993,222.990005,216.759995,222.149994,222.149994,29184000
4013,4013,4013,2018-10-17,222.300003,222.639999,219.339996,221.190002,221.190002,22885400
4014,4014,4014,2018-10-18,217.860001,219.740005,213.000000,216.020004,216.020004,32581300
4015,4015,4015,2018-10-19,218.059998,221.259995,217.429993,219.309998,219.309998,33078700
4016,4016,4016,2018-10-22,219.789993,223.360001,218.940002,220.649994,220.649994,28792100
4017,4017,4017,2018-10-23,215.830002,223.250000,214.699997,222.729996,222.729996,38767800
4018,4018,4018,2018-10-24,222.600006,224.229996,214.539993,215.089996,215.089996,40925500
4019,4019,4019,2018-10-25,217.710007,221.380005,216.750000,219.800003,219.800003,29855800
4020,4020,4020,2018-10-26,215.899994,220.190002,212.669998,216.300003,216.300003,47258400
4021,4021,4021,2018-10-29,219.190002,219.690002,206.089996,212.240005,212.240005,45935500
4022,4022,4022,2018-10-30,211.149994,215.179993,209.270004,213.300003,213.300003,36660000
4023,4023,4023,2018-10-31,216.880005,220.449997,216.619995,218.860001,218.860001,38358900
4024,4024,4024,2018-11-01,219.050003,222.360001,216.809998,222.220001,222.220001,58323200